[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/studio"
  to = "https://homewithbeth.sanity.studio"
  status = 301

[[redirects]]
  from = "/blog
  to = "/"
  status = 301

[[redirects]]
  from = "/blog/*
  to = "/"
  status = 301

[[redirects]]
  from = "/testimonials
  to = "/"
  status = 301